apiVersion: v1
kind: PersistentVolume
metadata:
  name: innovate-bank-mongodb
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteMany
  hostPath:
    path: /innovate