apiVersion: v1
kind: ConfigMap
metadata:
  name: "innovate-bank-configmap"
data:
  mongoUrl: "mongodb://mongo:mongo1234@test-db-mongodb:27017/admin"
  basePath: "place your public IP"
  sessionSecret: "5a4e0d2c6198976aaff66bc8"
  nodeEnv: "production"
  signupEndpoint: "/api/user/create"
  loginEndpoint: "/api/user/authenticate"
  getUsersEndpoint: "/api/user/get"
  getBillsEndpoint: "/api/bills/get"
  upsertBillEndpoint: "/api/bills/create"
  dropBillsEndpoint: "/api/bills/drop"
  createAccountEndpoint: "/api/accounts/create"
  getAccountsEndpoint: "/api/accounts/get"
  accountWithdrawEndpoint: "/api/accounts/withdraw"
  accountDepositEndpoint: "/api/accounts/deposit"
  dropAccountsEndpoint: "/api/accounts/drop"
  createTransactionEndpoint: "/api/transactions/create"
  getTransactionsEndpoint: "/api/transactions/get"
  dropTransactionsEndpoint: "/api/transactions/drop"
  chatEndpoint: "/api/message"
