apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "portal.fullname" . }}
  labels:
    app: {{ template "portal.name" . }}
    chart: {{ template "portal.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: "{{ template "portal.name" . }}-selector"
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: "{{ template "portal.name" . }}-selector"
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 3000
            periodSeconds: 1000
          env:
            - name: PORT
              value : "{{ .Values.service.port }}"
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: "{{ .Release.Name }}-innovate-bank-configmap"
                  key: nodeEnv
            - name: SESSION_SECRET
              valueFrom:
                configMapKeyRef:
                  name: "{{ .Release.Name }}-innovate-bank-configmap"
                  key: sessionSecret
            - name: MONGO_URL
              valueFrom:
                configMapKeyRef:
                  name: "{{ .Release.Name }}-innovate-bank-configmap"
                  key: mongoUrl
            - name: BASE_PATH
              valueFrom:
                configMapKeyRef:
                  name: "{{ .Release.Name }}-innovate-bank-configmap"
                  key: basePath
            - name: CREATE_TRANSACTION_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: "{{ .Release.Name }}-innovate-bank-configmap"
                  key: createTransactionEndpoint
            - name: ACCOUNT_WITHDRAW_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: "{{ .Release.Name }}-innovate-bank-configmap"
                  key: accountWithdrawEndpoint
            - name: ACCOUNT_DEPOSIT_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: "{{ .Release.Name }}-innovate-bank-configmap"
                  key: accountDepositEndpoint
            - name: CREATE_ACCOUNT_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: "{{ .Release.Name }}-innovate-bank-configmap"
                  key: createAccountEndpoint
            - name: GET_ACCOUNTS_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: "{{ .Release.Name }}-innovate-bank-configmap"
                  key: getAccountsEndpoint
            - name: UPSERT_BILL_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: "{{ .Release.Name }}-innovate-bank-configmap"
                  key: upsertBillEndpoint
            - name: GET_BILLS_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: "{{ .Release.Name }}-innovate-bank-configmap"
                  key: getBillsEndpoint
            - name: CHAT_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: "{{ .Release.Name }}-innovate-bank-configmap"
                  key: chatEndpoint
            - name: GET_TRANSACTIONS_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: "{{ .Release.Name }}-innovate-bank-configmap"
                  key: getTransactionsEndpoint
            - name: LOGIN_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: "{{ .Release.Name }}-innovate-bank-configmap"
                  key: loginEndpoint
            - name: SIGNUP_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: "{{ .Release.Name }}-innovate-bank-configmap"
                  key: signupEndpoint
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
